### ISSUE TITLE
support {{URL|}} form of website parameter

### ISSUE THREAD

**Issue by dachary** [Pascalco/harvesttemplates#91] opened 2016-09-26 15:58 UTC
In https://en.wikipedia.org/wiki/BIDS_Helper the website parameter of the software infobox has 
<pre>
|website                = {{URL|orienteering.sourceforge.net/drosera}}
</pre>
which is not a supported value for the [official website](https://www.wikidata.org/wiki/Property:P856) property. It should be converted into something shorter, possibly with a regexp.

**Comment by Pascalco** [comment] 2016-09-27 08:02
duplicate of #2

**Closed by Pascalco** 2016-09-27 08:02 UTC
Labels: duplicate
